{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "067ae4a0-5085-4821-8a57-22064e84129b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import gradio as gr\n",
    "from dotenv import load_dotenv\n",
    "from swarmauri.standard.llms.concrete.OpenAIToolModel import OpenAIToolModel as LLM\n",
    "from swarmauri.standard.conversations.concrete.Conversation import Conversation\n",
    "from swarmauri.standard.toolkits.concrete.Toolkit import Toolkit\n",
    "from swarmauri.standard.agents.concrete.ToolAgent import ToolAgent\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "64af7d95-1128-4ecd-89bf-1116719c842e",
   "metadata": {},
   "outputs": [],
   "source": [
    "load_dotenv()\n",
    "API_KEY = os.getenv('OPENAPI_API_KEY')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1cf35322-2447-419c-b211-0ba4af8e9895",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValidationError",
     "evalue": "1 validation error for OpenAIToolModel\napi_key\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValidationError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m tool_model \u001b[38;5;241m=\u001b[39m \u001b[43mLLM\u001b[49m\u001b[43m(\u001b[49m\u001b[43mapi_key\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mAPI_KEY\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\main.py:192\u001b[0m, in \u001b[0;36mBaseModel.__init__\u001b[1;34m(self, **data)\u001b[0m\n\u001b[0;32m    190\u001b[0m \u001b[38;5;66;03m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[39;00m\n\u001b[0;32m    191\u001b[0m __tracebackhide__ \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m--> 192\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__pydantic_validator__\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvalidate_python\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mself_instance\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "\u001b[1;31mValidationError\u001b[0m: 1 validation error for OpenAIToolModel\napi_key\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type"
     ]
    }
   ],
   "source": [
    "tool_model = LLM(api_key=API_KEY)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ac9f4836-dabf-4fdb-86c0-08101bcdafb7",
   "metadata": {},
   "source": [
    "### Custom Tool"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "1cd69c80-22ad-409e-afaa-53c7dd30fe3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List, Literal, Dict\n",
    "from pydantic import Field\n",
    "import subprocess as sp\n",
    "from swarmauri.standard.tools.base.ToolBase import ToolBase\n",
    "from swarmauri.standard.tools.concrete.Parameter import Parameter\n",
    "\n",
    "\n",
    "class CustomLinuxTool(ToolBase):\n",
    "    version: str = \"1.0.0\"\n",
    "    # Define the parameters required by the tool\n",
    "    parameters: List[Parameter] = Field(\n",
    "        default_factory=lambda: [\n",
    "            Parameter(\n",
    "                name=\"program\",\n",
    "                type=\"string\",\n",
    "                description=\"The program that the user wants to open or execute ('gnome-screenshot' or 'baobab' or 'evince')\",\n",
    "                required=True,\n",
    "                enum=[\"gnome-screenshot\", \"baobab\", \"evince\"],\n",
    "            )\n",
    "        ]\n",
    "    )\n",
    "    name: str = \"CustomLinuxTool\"\n",
    "    description: str = \"This opens or executes a program based on the user's request.\"\n",
    "    type: Literal[\"CustomLinuxTool\"] = \"CustomLinuxTool\"\n",
    "\n",
    "    def __call__(self, program) -> Dict[str, str]:\n",
    "        sp.check_output(program)\n",
    "        if program == 'gnome-screenshot':\n",
    "            return {\"program\": f\"Screenshot captured!\"}\n",
    "        return {\"program\": f\"Program Opened: {program}\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "3546aa0f-eb6f-4d01-9abc-55e92e5d0a59",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CustomLinuxTool(name='CustomLinuxTool', id='11359861-390f-4983-9e85-659218c6be4a', members=[], owner=None, host=None, resource='Tool', version='1.0.0', type='CustomLinuxTool', description=\"This opens or executes a program based on the user's request.\", parameters=[Parameter(name='program', id='465354a4-cf6c-493b-95ce-b08f1750dcba', members=[], owner=None, host=None, resource='Parameter', version='0.1.0', type='string', description=\"The program that the user wants to open or execute ('gnome-screenshot' or 'baobab' or 'evince')\", required=True, enum=['gnome-screenshot', 'baobab', 'evince'])])"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "CustomLinuxTool()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "ddae1597-4fa1-4996-aa06-1f66c4e426a4",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "toolkit = Toolkit(tools={\"CustomLinuxTool\": CustomLinuxTool()})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "274e79b7-a3be-41c8-ba41-c0b7d7e7e8ed",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Toolkit(name=None, id='08a2b6b5-fdc5-408c-bff5-5ceea9b721dd', members=[], owner=None, host=None, resource='Toolkit', version='0.1.0', type='Toolkit', tools={'CustomLinuxTool': CustomLinuxTool(name='CustomLinuxTool', id='67c17b5f-cd10-400b-93c4-34bbb4a69db2', members=[], owner=None, host=None, resource='Tool', version='1.0.0', type='CustomLinuxTool', description=\"This opens or executes a program based on the user's request.\", parameters=[Parameter(name='program', id='205b9c09-e285-4dbb-bdbd-ba70bd22702f', members=[], owner=None, host=None, resource='Parameter', version='0.1.0', type='string', description=\"The program that the user wants to open or execute ('gnome-screenshot' or 'baobab' or 'evince')\", required=True, enum=['gnome-screenshot', 'baobab', 'evince'])])})"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "toolkit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "f64fc76c-03a2-4ee0-ba6a-2bc2f2bbac74",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'tool_model' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[19], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m tool_agent \u001b[38;5;241m=\u001b[39m ToolAgent(\n\u001b[1;32m----> 2\u001b[0m     llm\u001b[38;5;241m=\u001b[39m\u001b[43mtool_model\u001b[49m,\n\u001b[0;32m      3\u001b[0m     conversation\u001b[38;5;241m=\u001b[39mConversation(),\n\u001b[0;32m      4\u001b[0m     toolkit\u001b[38;5;241m=\u001b[39mtoolkit\n\u001b[0;32m      5\u001b[0m )\n",
      "\u001b[1;31mNameError\u001b[0m: name 'tool_model' is not defined"
     ]
    }
   ],
   "source": [
    "tool_agent = ToolAgent(\n",
    "    llm=tool_model,\n",
    "    conversation=Conversation(),\n",
    "    toolkit=toolkit\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "0bad15db-3adb-4740-bb5d-985aaac0024c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7865\n",
      "IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.\n",
      "--------\n",
      "Running on public URL: https://3825b84b69382b1a01.gradio.live\n",
      "\n",
      "This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://3825b84b69382b1a01.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 277, in _init_core_attrs\n",
      "    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 119, in _getattr_no_parents\n",
      "    raise AttributeError(attribute)\n",
      "AttributeError: __pydantic_core_schema__\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 70, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 695, in __call__\n",
      "    await self.simple_response(scope, receive, send, request_headers=headers)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\gradio\\route_utils.py\", line 711, in simple_response\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n",
      "    raise exc\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\routing.py\", line 291, in app\n",
      "    solved_result = await solve_dependencies(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 656, in solve_dependencies\n",
      "    ) = await request_body_to_args(  # body_params checked above\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\dependencies\\utils.py\", line 881, in request_body_to_args\n",
      "    fields_to_extract = get_cached_model_fields(first_field.type_)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 657, in get_cached_model_fields\n",
      "    return get_model_fields(model)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 284, in get_model_fields\n",
      "    return [\n",
      "           ^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 285, in <listcomp>\n",
      "    ModelField(field_info=field_info, name=name)\n",
      "  File \"<string>\", line 6, in __init__\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\fastapi\\_compat.py\", line 110, in __post_init__\n",
      "    self._type_adapter: TypeAdapter[Any] = TypeAdapter(\n",
      "                                           ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 264, in __init__\n",
      "    self._init_core_attrs(rebuild_mocks=False)\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 142, in wrapped\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 284, in _init_core_attrs\n",
      "    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\type_adapter.py\", line 102, in _get_schema\n",
      "    schema = gen.generate_schema(type_)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 768, in _generate_schema_inner\n",
      "    return self._annotated_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1822, in _annotated_schema\n",
      "    schema = self._apply_annotations(source_type, annotations)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1890, in _apply_annotations\n",
      "    schema = get_inner_schema(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1972, in new_handler\n",
      "    schema = metadata_get_schema(source, get_inner_schema)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1968, in <lambda>\n",
      "    lambda source, handler: handler(source)\n",
      "                            ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_schema_generation_shared.py\", line 83, in __call__\n",
      "    schema = self._handler(source_type)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1871, in inner_handler\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 871, in match_type\n",
      "    return self._match_generic_type(obj, origin)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 895, in _match_generic_type\n",
      "    return self._union_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 1207, in _union_schema\n",
      "    choices.append(self.generate_schema(arg))\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 512, in generate_schema\n",
      "    schema = self._generate_schema_inner(obj)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 789, in _generate_schema_inner\n",
      "    return self.match_type(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 875, in match_type\n",
      "    return self._unknown_type_schema(obj)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\bigman\\anaconda3\\envs\\swarmauri-0.4.3\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py\", line 415, in _unknown_type_schema\n",
      "    raise PydanticSchemaGenerationError(\n",
      "pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.\n",
      "\n",
      "If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.\n",
      "\n",
      "For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type\n"
     ]
    }
   ],
   "source": [
    "# Define the function to be executed for the Gradio interface\n",
    "def tool_agent_interface(input_text, history):\n",
    "    # Directly pass the input_text (string) to tool_agent.exec\n",
    "    result = tool_agent.exec(input_text)\n",
    "    return result\n",
    "\n",
    "# Initialize the Gradio interface\n",
    "demo = gr.ChatInterface(tool_agent_interface)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(share=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cefdc348-38f6-4eb9-b202-469b14dbb9d5",
   "metadata": {},
   "source": [
    "### Customizing a Tool"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "0a092d93-e386-4dbc-a74c-a653e2eeb857",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List, Literal, Dict\n",
    "from pydantic import Field\n",
    "import subprocess as sp\n",
    "from swarmauri.standard.tools.base.ToolBase import ToolBase\n",
    "from swarmauri.standard.tools.concrete.Parameter import Parameter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "82ce52b4-2774-4a14-853b-c0d00ed4b4ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CustomGnomeTool(ToolBase): # We name the class\n",
    "    version: str = \"1.0.0\"\n",
    "\n",
    "    # Define the parameters required by the tool\n",
    "    parameters: List[Parameter] = Field(\n",
    "        default_factory=lambda: [\n",
    "            Parameter(\n",
    "                name=\"program\",\n",
    "                type=\"string\",\n",
    "                description=\"The program that the user wants to open ('gnome-control-center' or 'gnome-calendar' or 'gnome-terminal')\", \n",
    "                required=True,\n",
    "                enum=[\"gnome-control-center\", \"gnome-calendar\", \"gnome-terminal\"], # We define different values\n",
    "            )\n",
    "        ]\n",
    "    )\n",
    "    name: str = \"CustomGnomeTool\" # We change the tool's name attribute\n",
    "    description: str = \"This opens a gnome program based on the user's request.\" # We change the tool's name attribute\n",
    "    type: Literal[\"CustomGnomeTool\"] = \"CustomGnomeTool\" # We change the tool's type Literal, often this will match the name.\n",
    "\n",
    "    # Finally we customizing the __call__ function\n",
    "    def __call__(self, program) -> Dict[str, str]:\n",
    "        sp.check_output(program)\n",
    "        return {\"program\": f\"Gnome Program Opened: {program}\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "6c453712-1f6c-48d6-b595-fbc1373cc97e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CustomGnomeTool(name='CustomGnomeTool', id='63db6a0a-9de8-443b-ac2b-138c95f02f3c', members=[], owner=None, host=None, resource='Tool', version='1.0.0', type='CustomGnomeTool', description=\"This opens a gnome program based on the user's request.\", parameters=[Parameter(name='program', id='2f8552a8-037f-4494-91b9-33942058660e', members=[], owner=None, host=None, resource='Parameter', version='0.1.0', type='string', description=\"The program that the user wants to open ('gnome-control-center' or 'gnome-calendar' or 'gnome-terminal')\", required=True, enum=['gnome-control-center', 'gnome-calendar', 'gnome-terminal'])])"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "CustomGnomeTool()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "6f275c0c-2693-45b8-b2ae-6b2d3c0d4cb6",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Toolkit(name=None, id='c32e0528-4ea4-4098-bceb-07bed1310479', members=[], owner=None, host=None, resource='Toolkit', version='0.1.0', type='Toolkit', tools={'CustomGnomeTool': CustomGnomeTool(name='CustomGnomeTool', id='dcb7a404-82a0-408f-ad54-57e447cbfdc1', members=[], owner=None, host=None, resource='Tool', version='1.0.0', type='CustomGnomeTool', description=\"This opens a gnome program based on the user's request.\", parameters=[Parameter(name='program', id='1ae34b3b-4d8a-4158-b2ee-50e680d68fc3', members=[], owner=None, host=None, resource='Parameter', version='0.1.0', type='string', description=\"The program that the user wants to open ('gnome-control-center' or 'gnome-calendar' or 'gnome-terminal')\", required=True, enum=['gnome-control-center', 'gnome-calendar', 'gnome-terminal'])])})"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "toolkit = Toolkit(tools={\"CustomGnomeTool\": CustomGnomeTool()})\n",
    "toolkit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0103f791-3260-41c7-b473-912c7dc0cb2c",
   "metadata": {},
   "outputs": [],
   "source": [
    "tool_agent = ToolAgent(\n",
    "    llm=tool_model,\n",
    "    conversation=Conversation(),\n",
    "    toolkit=toolkit\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "392fe4d7-32a9-4e95-891a-bbae8f8d17b7",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# Define the function to be executed for the Gradio interface\n",
    "def tool_agent_interface(input_text, history):\n",
    "    # Directly pass the input_text (string) to tool_agent.exec\n",
    "    result = tool_agent.exec(input_text)\n",
    "    return result\n",
    "\n",
    "# Initialize the Gradio interface\n",
    "demo = gr.ChatInterface(tool_agent_interface)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(share=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
